### ISSUE TITLE
Kangrand.exe v2.2 Release

### ISSUE THREAD

**Issue by ashraful1980** [iceland2k14/Kangrand#1]
Dear Sir,
Could you please release updated windows Kangrand.exe v2.2; which is linux version.

Thanks & Regards,
Md. Ashraful Alam

**Comment by kpot87** [comment]
@ashraful1980 u can use Unix soft in windows 10 search at google

**Comment by iceland2k14** [comment]
Windows Updated Release, i already added in the "2.2_ed" 
I don't have Linux Release. You need to compile.
