### ISSUE TITLE
Real Result or BUG

### ISSUE THREAD

**Issue by ashraful1980** [iceland2k14/Kangrand#3]
Dear Sir,
Have a nice day and hope you are well.

I have run your program and find bellow result; i could not understand it is real or BUG????

I have tested 64 bit; as such it will finished less than 1 second; but it was still running 12 minutes. Please clear about the program...

![image](https://user-images.githubusercontent.com/52574658/114558595-a86cf700-9c8c-11eb-9a45-bf72df690a01.png)

**Comment by iceland2k14** [comment]
Ahh, you are giving incompatible options. The whole idea is either use **-st -en**  for the start and end of the range.
Or you can use **-rb -seq** to start from a random bitrange and check sequentially that much value.
Please correct the options, it will be fine.

**Comment by ashraful1980** [comment]
Dear Sir,
Thanks for your guidance....

Could you please making new project as missing char or WIF repair key tool for GPU version. Some project in github.com as like https://github.com/Coding-Enthusiast/FinderOuter but it was not a GPU version here.

Thanks & Regards,
Md. Ashraful Alam

**Comment by iceland2k14** [comment]
You can use this tool for WIF repair using GPU, it is based on Kangaroo algo
[https://github.com/PawelGorny/Kangaroo](https://github.com/PawelGorny/Kangaroo)
