### ISSUE TITLE
[XX] Pub: **** Aborted !

### ISSUE THREAD

**Issue by dextronomous** [iceland2k14/Kangrand#4]
hi there, is it possible that i am using your program wrongly, compressed and uncompressed mixed in file,
and searching 120 115 125 the way you explained here, rb seq m 1 ,  now i get a ton of aborted after each other,
how to fix, or is there another trick to use it, thanks a lot in advance.

**Comment by iceland2k14** [comment]
compressed and uncompressed mixed is not a problem.
m 1 is to use when we don't want to endlessly search the whole range. So it aborts itself after some time and move to next key.
Otherwise if you don't want that, just remove the option m 1 and run.

**Comment by dextronomous** [comment]
-d 2 -rb 120 -seq ffffffffffffff -st 800000000000000000000000000000 -en 8FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[28332330594087888.00 MK/s][GPU 28332330594087888.00 MK/s][Count 2^54][Dead 0][46:15 (Avg 00s)][2.0/4.0MB]

i'll get there eventually i guess, what you think boss, iceland2k14, you here, to use without -m 1
ender79, you said thanks working, but what did you got for an answer for your issue above. thanks.

**Comment by dextronomous** [comment]
[90248713526222224.00 MK/s][GPU 90248713526222224.00 MK/s][Count 2^56.37][Dead 0][6.8d (Avg 00s)][2.0/4.0MB]
its started going way faster

**Comment by dextronomous** [comment]
[364920914851401472.00 MK/s][GPU 164920914851401472.00 MK/s][Count 2^57.12][Dead 0][8.7d (Avg 00s)][2.0/4.0MB]

**Comment by dextronomous** [comment]
i have a new question sir, could you make a small change. verbose, to show the current range or keys it is working with / something like that. thank you.
