### ISSUE TITLE
aborted! Message

### ISSUE THREAD

**Issue by ender79** [iceland2k14/Kangrand#5]
C:\kang>Kangrand.exe -gpu -t 0  -m 1 -rb 256 -seq ffffffffffffff -st 49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5e0000000000000000 .\test.txt

Kangaroo v2.1 : Added Start End Options
Start:49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E0000000000000000
Stop :49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E002386F26FC10000
Keys :2
Number of CPU thread: 0
Range width: 2^54
Jump Avg distance: 2^27.02
Number of kangaroos: 2^21.52
Suggested DP: 2
Expected operations: 2^28.10
Expected RAM: 2747.3MB
DP size: 2 [0xC000000000000000]
GPU: GPU #0 NVIDIA GeForce RTX 3070 (46x128 cores) Grid(92x256) (237.0 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^21.52 kangaroos [6.8s]

Warning, 11925590 items lost
Hint: Search with less threads (-g) or increse dp (-d)
[177991640866.84 MK/s][GPU 177991640866.84 MK/s][Count 2^29.98][Dead 0][02s (Avg 00s)][90.0/124.8MB]
Key# 0 [XX]Pub:  0x0259A3BFDAD718C9D3FAC7C187F1139F0815AC5D923910D516E186AFDA28B221DC
       Aborted !
[0.00 MK/s][GPU 0.00 MK/s][Count 2^-inf][Dead 0][05s (Avg infy)][2.0/4.0MB]
Warning, 11927573 items lost
Hint: Search with less threads (-g) or increse dp (-d)
[1982434262.49 MK/s][GPU 1982434262.49 MK/s][Count 2^28.33][Dead 0][07s (Avg 06s)][30.0/63.0MB]
Key# 1 [XX]Pub:  0x0335BB25364370D4DD14A9FC2B406D398C4B53C85BE58FCC7297BD34004602EBEC
       Aborted !

GPU test Priv key not see screen and search continue ; 

C:\kang>Kangrand.exe -t 2  -m 1 -rb 256 -seq ffffffffffffff -st 49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5e0000000000000000 .\test.txt
Kangaroo v2.1 : Added Start End Options
Start:49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E0000000000000000
Stop :49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E002386F26FC10000
Keys :2
Number of CPU thread: 2
Range width: 2^54
Jump Avg distance: 2^27.02
Number of kangaroos: 2^11.00
Suggested DP: 13
Expected operations: 2^28.11
Expected RAM: 13.3MB
DP size: 13 [0xFFF8000000000000]
SolveKeyCPU Thread 0: 1024 kangaroos
SolveKeyCPU Thread 1: 1024 kangaroos
[252874733.92 MK/s][GPU 0.00 MK/s][Count 2^28.24][Dead 0][22s (Avg 18s)][3.2/9.6MB]
Key# 0 [XX]Pub:  0x0259A3BFDAD718C9D3FAC7C187F1139F0815AC5D923910D516E186AFDA28B221DC
       Aborted !
[260711247.36 MK/s][GPU 0.00 MK/s][Count 2^28.08][Dead 0][20s (Avg 17s)][3.1/9.0MB]
Key# 1 [1S]Pub:  0x0335BB25364370D4DD14A9FC2B406D398C4B53C85BE58FCC7297BD34004602EBEC
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E00034C1010000123

Key# 1 [XX]Pub:  0x0335BB25364370D4DD14A9FC2B406D398C4B53C85BE58FCC7297BD34004602EBEC
       Aborted !

Done: Total time 45s

CPU Test ; One Key Aborted message and One key priv key write screen.

Can you fix the bug? Thanks.

**Comment by ender79** [comment]
Kangrand.exe -gpu -t 0 -rb 256 -seq ffffffffffffff -st 800000000000000000000000000000 -en FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF .\test.txt

working thanks.

**Comment by dextronomous** [comment]
-d 2 -rb 120 -seq ffffffffffffff -st 800000000000000000000000000000 -en 8FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[28332330594087888.00 MK/s][GPU 28332330594087888.00 MK/s][Count 2^54][Dead 0][46:15 (Avg 00s)][2.0/4.0MB]

i'll get there eventually i guess, what you think boss, iceland2k14, you here,
ender79, you said thanks working, but what did you got for an answer for your issue above. thanks.
